# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight manually via xcodebuild"
  lane :beta do

    # 0. Разблокировка связки ключей (особенно важно при запуске через SSH)
    #sh "security unlock-keychain -p \"#{ENV['KEYCHAIN_PASSWORD']}\" ~/Library/Keychains/login.keychain-db"

    # 1. Увеличиваем build number
    increment_build_number(xcodeproj: "App.xcodeproj")
    )
    # 2. Архивация
    sh <<-EOS
      xcodebuild \
        -workspace ../App.xcworkspace \
        -scheme App \
        -sdk iphoneos \
        -configuration Release \
        -allowProvisioningUpdates \
        -archivePath ../build/App.xcarchive \
        archive
    EOS

    # 3. Экспорт ipa
    sh <<-EOS
      xcodebuild \
        -allowProvisioningUpdates \
        -exportArchive \
        -archivePath ../build/App.xcarchive \
        -exportOptionsPlist ./exportOptions.plist \
        -exportPath ../build
    EOS

    # 4. Загрузка в TestFlight    
    ipa_path = File.expand_path("../build/App.ipa", __dir__)

    upload_to_testflight(
      ipa: ipa_path,
      skip_waiting_for_build_processing: true,
      username: "dev@aydo.ai"
    )
  end
end

