platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "App.xcodeproj")

    sh <<-EOS
      xcodebuild \
        -workspace ../App.xcworkspace \
        -scheme App \
        -sdk iphoneos \
        -configuration Release \
        -allowProvisioningUpdates \
        -archivePath ../build/App.xcarchive \
        archive
    EOS

    sh <<-EOS
      xcodebuild \
        -allowProvisioningUpdates \
        -exportArchive \
        -archivePath ../build/App.xcarchive \
        -exportOptionsPlist ./fastlane/exportOptions_beta.plist \
        -exportPath ../build
    EOS

    ipa_path = File.expand_path("../build/App.ipa", __dir__)

    upload_to_testflight(
      ipa: ipa_path,
      skip_waiting_for_build_processing: true,
      username: "dev@aydo.ai"
    )
  end

  desc "Build and upload to App Store (release)"
  lane :release do
    increment_build_number(xcodeproj: "App.xcodeproj")

    sh <<-EOS
      xcodebuild \
        -workspace ../App.xcworkspace \
        -scheme App \
        -sdk iphoneos \
        -configuration Release \
        -allowProvisioningUpdates \
        -archivePath ../build/App.xcarchive \
        archive
    EOS

    sh <<-EOS
      xcodebuild \
        -allowProvisioningUpdates \
        -exportArchive \
        -archivePath ../build/App.xcarchive \
        -exportOptionsPlist ../fastlane/exportOptions_release.plist \
        -exportPath ../build
    EOS

    ipa_path = File.expand_path("../build/App.ipa", __dir__)

    upload_to_app_store(
      ipa: ipa_path,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      username: "dev@aydo.ai",
      submission_information: {
        export_compliance_uses_encryption: false,
        encryption_updated: false,
        app_type: "ios"
      }
    )
  end
end
