name: AYDO Client Prod Deploy

on:
  push:
    branches: [ "AYDO-main" ]
  pull_request:
    branches: [ "AYDO-main" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      name: trigger single Job
      uses: mickeygoussetorg/trigger-jenkins-job@v1
      with:
        jenkins-server:  "http://user:f1640b7c1df3496469a855262a451e95@jk.aydo.ai/"
        jenkins-job: "aydo_client" # The name of the jenkins job to run
        jenkins-username: "user"
        jenkins-pat: ${{ secrets.JENKINS_API_TOKEN }}
        verbose: true
    # - name: trigger single Job
    #   uses: appleboy/jenkins-action@master
    #   with:
    #     url: "http://user:f1640b7c1df3496469a855262a451e95@jk.aydo.ai/"
    #     user: "user"
    #     token: ${{ secrets.JENKINS_API_TOKEN }}
    #     job: "aydo_client"
